import { CardModel } from "./card-model"

export class Cards {

    public caves = [
        new CardModel(1, "Anão Louco", "/assets/cards/monsters/caves/anão-louco1.png", 4, 2),
        new CardModel(2, "Anão Louco", "/assets/cards/monsters/caves/anão-louco2.png", 4, 2),
        new CardModel(3, "Besouro Sísmico", "/assets/cards/monsters/caves/besouro-sismico.png", 4, 2),
        new CardModel(4, "Esqueleto Minerador", "/assets/cards/monsters/caves/esqueleto-minerador1.png", 2, 2),
        new CardModel(5, "Esqueleto Mirador", "/assets/cards/monsters/caves/esqueleto-mirador2.png", 2, 2),
        new CardModel(6, "Gigante das Cavernas", "/assets/cards/monsters/caves/gigante-das-cavernas.png", 5, 3),
        new CardModel(7, "Gigante das Cavernas", "/assets/cards/monsters/caves/gigante-das-cavernas2.png", 5, 3),
        new CardModel(8, "Golem de Pedra", "/assets/cards/monsters/caves/golem-pedra.png", 4, 4),
        new CardModel(9, "Homem-Lagarto Guerreiro", "/assets/cards/monsters/caves/homem-lagarto-guerreiro.png", 2, 2),
        new CardModel(10, "Homem-Lagarto Arqueiro", "/assets/cards/monsters/caves/homem-lagarto-arqueiro.png", 2, 2),
        new CardModel(11, "Homem-Morcego", "/assets/cards/monsters/caves/homem-morcego.png", 3, 2),
        new CardModel(12, "Homem-Rato", "/assets/cards/monsters/caves/homem-rato.png", 2, 2),
        new CardModel(13, "Larva Cinzenta", "/assets/cards/monsters/caves/larva-cinzenta.png", 1, 1),
        new CardModel(14, "Inseto Cinzento", "/assets/cards/monsters/caves/inseto-cinzento.png", 2, 1),
        new CardModel(15, "Formiga Operária", "/assets/cards/monsters/caves/formiga-operaria.png", 1, 1),
        new CardModel(16, "Morcego", "/assets/cards/monsters/caves/morcego.png", 1, 1, false),
        new CardModel(17, "Minotauro", "/assets/cards/monsters/caves/minotauro.png", 8, 6),
        new CardModel(18, "Ogro", "/assets/cards/monsters/caves/ogro.png", 3, 4),
        new CardModel(19, "Opilião", "/assets/cards/monsters/caves/opiliao.png", 3, 1),
        new CardModel(20, "Rastejador", "/assets/cards/monsters/caves/rastejador.png", 2, 2),
        new CardModel(21, "Vermes Escavadores", "/assets/cards/monsters/caves/vermes-escavadores.png", 4, 2),
        new CardModel(22, "Aranha de Sangue", "/assets/cards/monsters/caves/aranha-sangue.png", 2, 3),
        new CardModel(23, "Crias da Teia de Funil", "/assets/cards/monsters/caves/crias-teia-funil.png", 2, 2, false),
        new CardModel(24, "Teia de Funil", "/assets/cards/monsters/caves/teia-de-funil.png", 5, 2),
        new CardModel(25, "Basilisco", "/assets/cards/monsters/caves/basilisco.png", 5, 4),
        new CardModel(26, "Crocodilo Abissal", "/assets/cards/monsters/caves/crocodilo-abissal.png", 6, 4),
        new CardModel(27, "Escorpião de Pedra", "/assets/cards/monsters/caves/escorpião-pedra.png", 2, 2),
        new CardModel(28, "Gosma de Fogo", "/assets/cards/monsters/caves/gosma-fogo.png", 2, 1),
        new CardModel(29, "Monstro da Névoa", "/assets/cards/monsters/caves/monstro-da-nevoa.png", 5, 4),
        new CardModel(30, "Monstro das Sombras", "/assets/cards/monsters/caves/monstro-sombra.png", 2, 2),
        new CardModel(31, "Ork Bruto", "/assets/cards/monsters/caves/ork-bruto.png", 4, 3),
        new CardModel(32, "Ork Bruto Blindado", "/assets/cards/monsters/caves/ork-bruto-armor.png", 4, 3),
        new CardModel(33, "Ork Mago de Fogo", "/assets/cards/monsters/caves/ork-mago-fogo.png", 2, 2),
        new CardModel(34, "Ork Mago de Gelo", "/assets/cards/monsters/caves/ork-mago-gelo.png", 2, 2),
        new CardModel(35, "Pedregoso", "/assets/cards/monsters/caves/pedregoso.png", 3, 4),
        new CardModel(36, "Succubus", "/assets/cards/monsters/caves/succubus.png", 3, 3),
        new CardModel(37, "Troll das Cavernas", "/assets/cards/monsters/caves/troll-das-cavernas.png", 3, 3),
    ];

    public mountains = [
        new CardModel(38, "Barata Mutante", "/assets/cards/monsters/mountains/barata-mutante.png", 2, 1),
        new CardModel(39, "Bruxa da Montanha", "/assets/cards/monsters/mountains/bruxa-montanha.png", 6, 0, false),
        new CardModel(40, "Centauro Arqueiro", "/assets/cards/monsters/mountains/centauro-arqueiro.png", 3, 2),
        new CardModel(41, "Centauro Guerreiro", "/assets/cards/monsters/mountains/centauro-guerreiro.png", 5, 4),
        new CardModel(42, "Cogumelo Carnívoro", "/assets/cards/monsters/mountains/cogumelo-carnivoro.png", 2, 1),
        new CardModel(43, "Diabrete", "/assets/cards/monsters/mountains/diabrete.png", 3, 2),
        new CardModel(44, "Elemental do Vento", "/assets/cards/monsters/mountains/elemental-vento.png", 4, 1),
        new CardModel(45, "Elfo Ladrão", "/assets/cards/monsters/mountains/elfo-ladrao.png", 2, 2),
        new CardModel(46, "Escorpião-Aranha", "/assets/cards/monsters/mountains/escorpião-aranha.png", 6, 5),
        new CardModel(47, "Gárgola Adormecida", "/assets/cards/monsters/mountains/gargola-adormecida.png", 5, 3),
        new CardModel(48, "Gato Ilusionista", "/assets/cards/monsters/mountains/gato-ilusionista.png", 6, 0, false),
        new CardModel(49, "Harpia", "/assets/cards/monsters/mountains/harpia.png", 1, 1),
        new CardModel(50, "Lobo Alfa", "/assets/cards/monsters/mountains/lobo-alpha.png", 3, 3),
        new CardModel(51, "Lobo Cinzento", "/assets/cards/monsters/mountains/lobo-cinzento.png", 2, 2),
        new CardModel(52, "Mímico", "/assets/cards/monsters/mountains/mimico.png", 1, 1),
        new CardModel(53, "Mímico de Pedra", "/assets/cards/monsters/mountains/mimico-pedra.png", 4, 3),
        new CardModel(54, "Mosquito Gigante", "/assets/cards/monsters/mountains/mosquito-gigante.png", 1, 1, false),
        new CardModel(55, "Tubarão Andarilho", "/assets/cards/monsters/mountains/tubarao-andarilho.png", 3, 2),
        new CardModel(56, "Troll de Pedra", "/assets/cards/monsters/mountains/troll-pedra.png", 10, 5),
        new CardModel(57, "Urso", "/assets/cards/monsters/mountains/urso.png", 2, 4),
        new CardModel(58, "Urso de Gelo", "/assets/cards/monsters/mountains/urso-de-gelo.png", 4, 4),
    ];

    public ruins = [
        new CardModel(59, "Andarilho Possuído", "/assets/cards/monsters/ruins/andarilho-possuido2.png", 2, 2),
        new CardModel(60, "Arqueiro", "/assets/cards/monsters/ruins/arqueiro.png", 1, 2),
        new CardModel(61, "Assassino Mascarado", "/assets/cards/monsters/ruins/assassino-mascarado.png", 2, 2),
        new CardModel(62, "Bêbado Enfurecido", "/assets/cards/monsters/ruins/bebado-enfurecido.png", 3, 1),
        new CardModel(63, "Berserker", "/assets/cards/monsters/ruins/berserker.png", 5, 3),
        new CardModel(64, "Cão Raivoso", "/assets/cards/monsters/ruins/cao-raivoso.png", 1, 1),
        new CardModel(65, "Cultista Ascendido", "/assets/cards/monsters/ruins/cultista-ascendido.png", 2, 3),
        new CardModel(66, "Cultista Fanático", "/assets/cards/monsters/ruins/cultista-fanatico1.png", 2, 2),
        new CardModel(67, "Cultista Fanático Ancião", "/assets/cards/monsters/ruins/cultista-fanatico2.png", 2, 2),
        new CardModel(68, "Desconhecido", "/assets/cards/monsters/ruins/desconhecido.png", 6, 6),
        new CardModel(69, "Devoto da Chama Negra", "/assets/cards/monsters/ruins/devoto-chama-negra.png", 2, 2),
        new CardModel(70, "Elfo Caído da Guarda Real", "/assets/cards/monsters/ruins/elfo-caido-guarda-real.png", 3, 3),
        new CardModel(71, "Elfo Corrompido", "/assets/cards/monsters/ruins/elfo-corrompido.png", 2, 3),
        new CardModel(72, "Espectro das Ruínas", "/assets/cards/monsters/ruins/espectro-das-ruinas.png", 2, 2),
        new CardModel(73, "Feiticeira Urbana", "/assets/cards/monsters/ruins/feiticeira-urbana.png", 1, 3),
        new CardModel(74, "Ghoul", "/assets/cards/monsters/ruins/ghoul.png", 2, 1),
        new CardModel(75, "Guarda Corrupto", "/assets/cards/monsters/ruins/guarda-corrupto.png", 3, 2),
        new CardModel(76, "Guarda Corrupto Veterano", "/assets/cards/monsters/ruins/guarda-corrupto2.png", 3, 2),
        new CardModel(77, "Ladrão", "/assets/cards/monsters/ruins/ladrão.png", 2, 1),
        new CardModel(78, "Ladrão de Almas", "/assets/cards/monsters/ruins/ladrão-almas.png", 4, 2),
        new CardModel(79, "Ladrão de Memórias", "/assets/cards/monsters/ruins/ladrao-memorias.png", 2, 2),
        new CardModel(80, "Mago", "/assets/cards/monsters/ruins/mago.png", 2, 3),
        new CardModel(81, "Mago da Chama Negra", "/assets/cards/monsters/ruins/mago-chama-negra.png", 4, 3),
        new CardModel(82, "Mago da Chama Negra Ancião", "/assets/cards/monsters/ruins/mago-chama-negra2.png", 4, 3),
        new CardModel(83, "Mago Negro", "/assets/cards/monsters/ruins/mago-negro.png", 3, 4),
        new CardModel(84, "Mercenário", "/assets/cards/monsters/ruins/mercenario.png", 2, 3),
        new CardModel(85, "Rato das Catacumbas", "/assets/cards/monsters/ruins/rato-catacumbas.png", 5, 2),
        new CardModel(86, "Rato do Esgoto", "/assets/cards/monsters/ruins/rato-esgoto.png", 1, 2, false),
        new CardModel(87, "Ratos das Ruínas", "/assets/cards/monsters/ruins/ratos-das-ruinas.png", 2, 3, false),
        new CardModel(88, "Ronin Perseguido", "/assets/cards/monsters/ruins/ronin-perseguido.png", 2, 3, false),
        new CardModel(89, "Sword Maiden", "/assets/cards/monsters/ruins/sword-maiden.png", 3, 3),
        new CardModel(90, "Vampira", "/assets/cards/monsters/ruins/vampira1.png", 5, 2),
        new CardModel(91, "Vampira Anciã", "/assets/cards/monsters/ruins/vampira2.png", 5, 2),
        new CardModel(92, "Vampiro", "/assets/cards/monsters/ruins/vampiro1.png", 5, 3),
    ];

    public undead = [
        new CardModel(93, "A Sombra", "/assets/cards/monsters/undead/a-sombra.png", 1, 1),
        new CardModel(94, "Cães Esqueleto", "/assets/cards/monsters/undead/caes-esqueleto.png", 2, 2, false),
        new CardModel(95, "Carniçal Recém-Erguido", "/assets/cards/monsters/undead/carniçal-recem.png", 3, 2),
        new CardModel(96, "Carniçal Semi-Decomposto", "/assets/cards/monsters/undead/carniçal-semi.png", 4, 3),
        new CardModel(97, "Carniçal Completo", "/assets/cards/monsters/undead/carniçal-completo.png", 5, 4),
        new CardModel(98, "Cavaleiro Sem Cabeça", "/assets/cards/monsters/undead/cavaleiro-sem-cabeça.png", 3, 2),
        new CardModel(99, "Espírito Errante", "/assets/cards/monsters/undead/espirito-errante.png", 4, 2),
        new CardModel(100, "Esqueleto Arqueiro", "/assets/cards/monsters/undead/esqueleto-arqueiro.png", 2, 2),
        new CardModel(101, "Esqueleto Arqueiro Veterano", "/assets/cards/monsters/undead/esqueleto-arqueiro2.png", 2, 2),
        new CardModel(102, "Esqueleto Berserker", "/assets/cards/monsters/undead/esqueleto-berserker.png", 2, 4),
        new CardModel(103, "Esqueleto em Chamas", "/assets/cards/monsters/undead/esqueleto-chamas.png", 2, 1),
        new CardModel(104, "Esqueleto de Elite", "/assets/cards/monsters/undead/esqueleto-de-elite.png", 3, 3),
        new CardModel(105, "Fantasma Aflito", "/assets/cards/monsters/undead/fantasma-aflito.png", 2, 1),
        new CardModel(106, "Fantasma Aflito Ancião", "/assets/cards/monsters/undead/fantasma-aflito2.png", 2, 1),
        new CardModel(107, "Guerreiro Sem Cabeça", "/assets/cards/monsters/undead/guerreiro-sem-cabeça.png", 3, 2),
        new CardModel(108, "Necromante", "/assets/cards/monsters/undead/necromante.png", 2, 2),
        new CardModel(109, "O Carrasco", "/assets/cards/monsters/undead/o-carrasco.png", 4, 4),
        new CardModel(110, "Zumbi Costurado", "/assets/cards/monsters/undead/zumbi-costurado.png", 3, 0, false),
        new CardModel(111, "Zumbi Hospedeiro", "/assets/cards/monsters/undead/zumbi-hospedeiro.png", 4, 3),
        new CardModel(112, "Zumbi Lento", "/assets/cards/monsters/undead/zumbi-lento.png", 3, 1),
        new CardModel(113, "Zumbi Tóxico", "/assets/cards/monsters/undead/zumbi-toxico.png", 3, 1),
    ];

    public woods = [
        new CardModel(114, "Afogador", "/assets/cards/monsters/woods/afogador.png", 4, 2),
        new CardModel(115, "Aragrog", "/assets/cards/monsters/woods/aragrog.png", 2, 2),
        new CardModel(116, "Aranha Espreitadora", "/assets/cards/monsters/woods/aranha-espreitadora.png", 2, 2),
        new CardModel(117, "Árvore Andarilha", "/assets/cards/monsters/woods/arvore-andarilha.png", 4, 2),
        new CardModel(118, "Bruxa Fada", "/assets/cards/monsters/woods/bruxa-fada.png", 3, 3),
        new CardModel(119, "Bruxa do Pântano", "/assets/cards/monsters/woods/bruxa-pantano.png", 3, 4),
        new CardModel(120, "Caçador Sem Face", "/assets/cards/monsters/woods/caçador-sem-face.png", 3, 3),
        new CardModel(121, "Caçador Sem Face Ancião", "/assets/cards/monsters/woods/caçador-sem-face2.png", 3, 3),
        new CardModel(122, "Cervo Zumbi", "/assets/cards/monsters/woods/cervo-zumbi.png", 2, 2),
        new CardModel(123, "Corvos Carniceiros", "/assets/cards/monsters/woods/corvos-carniceiros.png", 1, 1),
        new CardModel(124, "Desconhecido", "/assets/cards/monsters/woods/desconhecido.png", 6, 5),
        new CardModel(125, "Ent Amaldiçoado", "/assets/cards/monsters/woods/ent-amaldiçoado.png", 5, 3),
        new CardModel(126, "Ent Espinhoso", "/assets/cards/monsters/woods/ent-espinhoso.png", 3, 1),
        new CardModel(127, "Esquilos Inofensivos", "/assets/cards/monsters/woods/esquilos-inofensivos.png", 1, 1, false),
        new CardModel(128, "Feiticeira do Pântano", "/assets/cards/monsters/woods/feiticeira-pantano.png", 4, 4),
        new CardModel(129, "Flor Carnívora", "/assets/cards/monsters/woods/flor-carnivora.png", 6, 2),
        new CardModel(130, "Flor Venenosa", "/assets/cards/monsters/woods/flor-venenosa.png", 5, 2),
        new CardModel(131, "Goblin Bruto", "/assets/cards/monsters/woods/goblin-bruto.png", 4, 4),
        new CardModel(132, "Goblin Covarde", "/assets/cards/monsters/woods/goblin-covarde.png", 2, 2),
        new CardModel(133, "Goblin Guerreiro", "/assets/cards/monsters/woods/goblin-guerreiro.png", 2, 3),
        new CardModel(134, "Goblin Ladrão", "/assets/cards/monsters/woods/goblin-ladrão.png", 1, 1),
        new CardModel(135, "Gosma Roxa", "/assets/cards/monsters/woods/gosma-roxa.png", 4, 1),
        new CardModel(136, "Hemófago", "/assets/cards/monsters/woods/hemofago.png", 5, 3),
        new CardModel(137, "Homem-Serpente", "/assets/cards/monsters/woods/homem-serpente.png", 2, 3),
        new CardModel(138, "Javali Comum", "/assets/cards/monsters/woods/javali-comum.png", 2, 1),
        new CardModel(139, "Lich", "/assets/cards/monsters/woods/lich.png", 3, 2),
        new CardModel(140, "Licantropo", "/assets/cards/monsters/woods/licantropo.png", 6, 5),
        new CardModel(141, "Lobo Cinzento", "/assets/cards/monsters/woods/lobo-cinzento.png", 2, 2),
        new CardModel(142, "Nevuloso", "/assets/cards/monsters/woods/nevuloso.png", 3, 2),
        new CardModel(143, "Ninfa Ilusória", "/assets/cards/monsters/woods/ninfa-ilusoria.png", 4, 0, false),
        new CardModel(144, "Planta Carnívora", "/assets/cards/monsters/woods/planta-carnivora.png", 6, 2),
        new CardModel(145, "Rato Gigante", "/assets/cards/monsters/woods/rato-gigante.png", 2, 1),
        new CardModel(146, "Sanguessuga", "/assets/cards/monsters/woods/sanguessuga.png", 4, 2),
        new CardModel(147, "Sapo Venenoso", "/assets/cards/monsters/woods/sapo-venenoso.png", 2, 1),
        new CardModel(148, "Urso Blindado", "/assets/cards/monsters/woods/urso-blindado.png", 4, 4),
        new CardModel(149, "Vespa Assassina", "/assets/cards/monsters/woods/vespa-assassina.png", 1, 2),
        new CardModel(150, "Víbora Cega", "/assets/cards/monsters/woods/vibora-cega.png", 4, 3),
    ];

    public allMonsters = [...this.caves, ...this.mountains, ...this.ruins, ...this.undead, ...this.woods];

    public bosses = [
        new CardModel(1, "Aranha-Mãe", "/assets/cards/bosses/aranha-mae.png", 20, 6),
        new CardModel(2, "Arauto do Fim", "/assets/cards/bosses/arauto-do-fim.png", 50, 5),
        new CardModel(3, "Arqueomante de Ossos", "/assets/cards/bosses/arqueomante-de-ossos.png", 20, 6),
        new CardModel(4, "Arqueomante Proibido", "/assets/cards/bosses/arqueomante-proibido.png", 15, 8),
        new CardModel(5, "Cavaleiro Pálido", "/assets/cards/bosses/cavaleiro-palido.png", 15, 7),
        new CardModel(6, "Colosso de Ferro", "/assets/cards/bosses/colosso-de-ferro.png", 15, 7),
        new CardModel(7, "Drácula", "/assets/cards/bosses/dracula.png", 20, 6),
        new CardModel(8, "Flagelo das Almas", "/assets/cards/bosses/flagelo-das-almas.png", 12, 3),
        new CardModel(9, "Flor Maldita de Ylliria", "/assets/cards/bosses/flor-maldita-ylliria.png", 10, 6),
        new CardModel(10, "Matriarca das Serpentes", "/assets/cards/bosses/matriarca-serpentes.png", 20, 7),
        new CardModel(11, "O Abissal", "/assets/cards/bosses/o-abissal.png", 15, 9),
        new CardModel(12, "O Açougueiro", "/assets/cards/bosses/o-acougueiro.png", 25, 7),
        new CardModel(13, "Rainha Abissal", "/assets/cards/bosses/rainha-abissal.png", 20, 7),
        new CardModel(14, "Ulrik", "/assets/cards/bosses/ulrick.png", 10, 9),
        new CardModel(15, "Voragun", "/assets/cards/bosses/voragun.png", 20, 7)
    ];
}
