import { CardModel } from "./card-model"
import { Story } from "./story";
import { StoryBlock } from "./story-block";

export class Stories {
    public stories = [
        new Story(1, "A Maldição da Floresta Sussurrante",
            [
                new StoryBlock(1, "Início da Jornada", "Vocês chegam na pequena vila de Pedraverde. O ar é pesado, e uma névoa gelada e úmida paira sobre as ruas. Os moradores se escondem, olhando para a floresta como se fosse um monstro vivo. A Helga, a chefe da guarda, uma mulher forte, com a cara séria e cicatrizes de batalhas, está esperando vocês. Ela aponta para um mapa na mesa e diz:'A floresta... ela tá doente', Helga fala, com a voz grave. 'Não é só a névoa, é o que ela faz. Os caçadores que sumiram não foram mortos... eles foram mudados. A gente precisa que vocês entrem lá, achem a fonte disso tudo e acabem com essa maldição antes que ela chegue aqui na vila. Nossas esperanças estão nas mãos de vocês, então por favor, sejam os heróis que precisamos.", "village", "", 1, false),
                new StoryBlock(2, "Encontro 1", "A névoa é tão espessa que o sol da manhã não passa de um ponto pálido e distante no céu, incapaz de penetrar a brancura úmida que engole a Floresta Sussurrante. O mundo se contrai para um círculo de poucos metros ao seu redor, e a trilha, que deveria ser a única coisa que os guia, se desfaz sob a brancura. O ar tem um cheiro forte de terra molhada e folhas em decomposição, e o silêncio é total, quebrado só pelo barulho abafado dos seus próprios passos e o som de galhos secos se partindo sob os pés de vocês. De repente, vocês se deparam com a mochila de um dos caçadores que sumiram, caída no chão. Ao lado dela, uma marca estranha no chão, como se algo pesado tivesse sido arrastado para dentro do mato. A floresta não está vazia, ela apenas está à espreita, e a névoa esconde algo mais do que apenas árvores e sombras.", "forest", "woods", 1, false),
                new StoryBlock(3, "Encontro 2", "A trilha se abre um pouco, e a névoa, por um momento, dá uma trégua. Vocês chegam num riacho de águas cristalinas que serpentia por entre raízes e pedras com musgo. A beleza do local contrasta com o ar pesado da floresta, e o murmúrio suave da água é um alívio. No entanto, vocês notam algo estranho: alguns peixes flutuam mortos, e a água, apesar de clara, parece ter um brilho leitoso, como se estivesse doente. A tensão está no ar, e um uivo distante ecoa entre as árvores. Vocês ouvem um movimento na água e percebem que algo se esconde nas margens, pronto para atacar", "forest", "woods", 2, false),
                new StoryBlock(4, "Ponto de Descanso", "A batalha nas margens do riacho termina, e a brisa suave do entardecer sopra a névoa para longe temporariamente. A beleza natural do lugar, com o som da água correndo e o canto distante dos pássaros, oferece um refúgio sereno. Vocês podem acampar, afiar suas armas, cuidar dos machucados e se preparar para a jornada pela trilha sinuosa que se aproxima.", "forest", "", 3, false),
                new StoryBlock(5, "Encontro 3", "O sol vai embora e pinta o céu com tons alaranjados e roxos que mal conseguem furar o manto da névoa que se adensa novamente. A trilha à sua frente se torna sinuosa, e as árvores parecem se fechar sobre vocês, suas copas retorcidas se transformando em dedos fantasmagóricos. O ar fica mais gelado, e a tensão aumenta. A névoa parece voltar mais forte. Vocês notam que alguns galhos parecem ter sido quebrados à força, e no chão, a grama está pisoteada. Não parece ser um caminho de animais, mas de algo grande e pesado que foi arrastado por ali.", "forest", "woods", 3, false),
                new StoryBlock(6, "Encontro 4", "A floresta some do nada, e vocês chegam num campo enorme coberto de pedras e escombros, como se uma cidade inteira tivesse sido esmagada e largada ali. A névoa por aqui é mais escura, quase cinzenta, e tem um cheiro forte de pedra fria e poeira milenar. A luz pálida da lua ilumina as colunas quebradas e as estátuas caídas de uma civilização élfica antiga. As ruínas, que antes eram grandiosas, agora parecem esqueletos de pedra, e vocês sentem que algo se move entre os vestígios da história, observando cada passo.", "cave", "caves", 4, false),
                new StoryBlock(7, "Ponto de Descanso", "Após a batalha, a névoa das ruínas desaparece, revelando uma vista para um lago tranquilo e prateado à luz da lua. O pátio em que vocês estão oferece um refúgio seguro, onde podem fazer uma fogueira e descansar, sentindo a brisa fresca que vem da água. É um momento de calmaria para se reequiparem e discutirem o que o espera na parte mais profunda das ruínas.", "cave", "", 5, false),
                new StoryBlock(8, "Encontro 5", "A noite é total nas ruínas. O vento frio assobia entre as colunas quebradas, e cada eco parece carregar os sussurros de almas perdidas. Não são vozes aleatórias, mas sim fragmentos de tristeza e desespero de um povo que já foi grande, lamentando seu destino. As ruínas, mal-assombradas, parecem mais um labirinto fantasma do que um lugar físico. Um som metálico, como o ranger de uma máquina antiga, ecoa ao longe. A cada passo, a sensação de que não estão sozinhos só aumenta, como se estivessem caminhando no meio de uma batalha que aconteceu há séculos, mas que nunca terminou.", "cave", "caves", 5, false),           
                new StoryBlock(9, "Encontro 6", "O amanhecer traz uma luz fraca. Vocês chegam ao que parece ser o pátio central das ruínas. A névoa se dissipa levemente, e vocês veem a entrada de uma tumba élfica, imponente e coberta de musgo. Um cheiro de terra molhada e mofo se torna forte.", "cave", "caves", 6, false),                      
                new StoryBlock(10, "Ponto de Descanso", "Depois de atravessar as ruínas, vocês dão de cara com o imponente pátio da tumba élfica. A névoa parece temer este lugar, dissipando-se em uma brisa suave que carrega o cheiro de pedra antiga e musgo. Entre as estátuas caídas e arcos rachados, há um local abrigado e silencioso. É um momento de calmaria antes da tempestade, onde vocês podem recarregar as energias, planejar a estratégia e preparar o espírito para a escuridão que os aguarda lá dentro.", "cave", "", 7, false),
                new StoryBlock(11, "Encontro 7", "A porta da tumba se abre com um rangido assustador. Uma escuridão profunda os recebe. Vocês se veem em um corredor estreito e úmido, iluminado apenas por suas tochas ou fontes de luz. A voz de um dos jogadores ecoa nos seus pensamentos: 'A maldição não é do mundo exterior. É do que está lá dentro.'", "cave", "undead", 7, false),                      
                new StoryBlock(12, "Encontro 8", "Vocês se aprofundam na tumba, passando por corredores sinuosos e úmidos. As paredes estão cobertas de símbolos élficos que parecem se mover e tremer à luz bruxuleante. O ar é denso, e o silêncio é quebrado apenas por gotas d'água caindo. Vocês percebem que não estão sozinhos nas profundezas escuras.", "cave", "undead", 8, false),                      
                new StoryBlock(13, "Ponto de Descanso", "Vocês encontram uma pequena câmara lateral, com runas mágicas brilhando nas paredes. A magia élfica ainda presente no local parece repelir a névoa da maldição, criando uma bolha de ar fresco e tranquilo. Este é o último refúgio antes do confronto final. É a chance de curar as feridas, afiar as lâminas e se preparar para o que os espera na câmara mais profunda.", "cave", "", 9, false),
                new StoryBlock(14, "Encontro 9", "Vocês se aproximam da câmara final. A névoa volta, mas com uma cor preta e espessa. Ela se move e se contorce, como se estivesse viva. O ar fica gelado, e a sensação de morte é avassaladora. De repente, a névoa ganha forma, e criaturas esqueléticas e espectrais emergem das sombras.", "cave", "undead", 9, false),
                new StoryBlock(15, "Ponto de Descanso", "A batalha na câmara final deixa um rastro de névoa negra e sombras. No chão, um círculo mágico de cura se ilumina, brilhando com uma luz dourada e suave que afasta o frio da morte. Ele foi ativado pela derrota das criaturas amaldiçoadas e oferece uma última oportunidade para curar suas feridas, afiar suas lâminas e se fortalecerem para o confronto decisivo. É o ponto de não-retorno, a última chance de respirar fundo antes de enfrentar a fonte da maldição.", "cave", "", 10, false),
                new StoryBlock(16, "Ato Final", "Vocês adentram a câmara final. O espaço se expande em uma vasta caverna subterrânea, o ar incrivelmente pesado e carregado de uma energia sinistra. No centro, um cristal negro do tamanho de um homem adulto pulsa com uma luz opaca e maligna, como um coração doente bombeando escuridão para toda a floresta. A névoa negra que assola a superfície aqui é densa como um manto, girando ao redor do cristal e se estendendo em tentáculos sombrios pelas paredes da caverna. O chão é feito de pedra irregular, coberto por uma fina camada de poeira e fragmentos de ossos antigos. Runas élficas corrompidas brilham fracamente nas paredes, pulsando em sincronia com o cristal, como se estivessem aprisionando ou alimentando sua energia. Um frio intenso emana do cristal, penetrando suas roupas e congelando a respiração em seus pulmões. Diante do cristal, paira uma figura esquelética, envolta em mantos élficos esfarrapados que já foram majestosos, mas agora estão gastos e manchados pela corrupção. Em suas mãos ossudas, ele segura um cajado retorcido, feito de madeira escura e adornado com fragmentos do mesmo cristal negro. Olhos vermelhos e vazios fitam vocês, carregados de uma maldade antiga e de um poder que corrompeu toda a floresta. A fonte da maldição da Floresta Sussurrante finalmente se revela.", "cave", "undead", 10, true),
                new StoryBlock(17, "O Silêncio Após a Névoa", "O cristal negro estala uma última vez. As runas élficas corrompidas nas paredes piscam de forma errática e, então, se apagam. Um som grave e profundo ecoa pela caverna, como um suspiro antigo sendo finalmente libertado. A figura esquelética diante de vocês se desfaz em poeira acinzentada, levada por uma corrente de ar frio que percorre toda a tumba. O cristal, agora rachado, perde o brilho sombrio e se parte em fragmentos inertes, espalhando-se pelo chão como vidro morto.\n\nA névoa negra começa a recuar. Primeiro dentro da caverna, depois pelos corredores da tumba, como se estivesse sendo puxada de volta para um lugar que não deveria mais existir. O ar fica mais leve, e pela primeira vez desde que entraram na floresta, vocês respiram sem sentir o peso da maldição nos pulmões.\n\nAo retornarem à superfície, o amanhecer rompe as copas das árvores. A Floresta Sussurrante está diferente. A névoa desapareceu quase por completo, os galhos retorcidos parecem menos ameaçadores, e o canto tímido de pássaros ecoa entre as árvores. O silêncio opressor foi substituído por um murmúrio natural de vida retomando seu espaço.\n\nDe volta à vila de Pedraverde, Helga os recebe em silêncio, observando o céu limpo com os olhos marejados. 'Então… acabou', ela diz, com um misto de alívio e incredulidade. Os moradores saem de suas casas, ainda desconfiados, mas aos poucos a esperança toma conta do lugar. Vocês não são recebidos apenas como mercenários ou aventureiros, mas como aqueles que enfrentaram uma maldição antiga e devolveram o futuro à vila.\n\nEmbora a floresta nunca esqueça completamente o que aconteceu, a fonte da corrupção foi destruída. As ruínas élficas permanecem como um lembrete silencioso do preço da arrogância e da magia mal utilizada. E vocês seguem viagem, sabendo que deixaram para trás um lugar marcado pela escuridão… mas também pela redenção.", "village", "", 10, false)
            ]
        )
    ];
}