import { CardModel } from "./card-model"
import { Story } from "./story";
import { StoryBlock } from "./story-block";

export class Stories {
    public stories = [
        new Story(1, "A Maldição da Floresta Sussurrante", "sage",
            [
                new StoryBlock(1, "Início da Jornada", "Vocês chegam na pequena vila de Pedraverde. O ar é pesado, e uma névoa gelada e úmida paira sobre as ruas. Os moradores se escondem, olhando para a floresta como se fosse um monstro vivo. A Helga, a chefe da guarda, uma mulher forte, com a cara séria e cicatrizes de batalhas, está esperando vocês. Ela aponta para um mapa na mesa e diz:'A floresta... ela tá doente', Helga fala, com a voz grave. 'Não é só a névoa, é o que ela faz. Os caçadores que sumiram não foram mortos... eles foram mudados. A gente precisa que vocês entrem lá, achem a fonte disso tudo e acabem com essa maldição antes que ela chegue aqui na vila. Nossas esperanças estão nas mãos de vocês, então por favor, sejam os heróis que precisamos.", "village", "", 1, false),
                new StoryBlock(2, "Encontro 1", "A névoa é tão espessa que o sol da manhã não passa de um ponto pálido e distante no céu, incapaz de penetrar a brancura úmida que engole a Floresta Sussurrante. O mundo se contrai para um círculo de poucos metros ao seu redor, e a trilha, que deveria ser a única coisa que os guia, se desfaz sob a brancura. O ar tem um cheiro forte de terra molhada e folhas em decomposição, e o silêncio é total, quebrado só pelo barulho abafado dos seus próprios passos e o som de galhos secos se partindo sob os pés de vocês. De repente, vocês se deparam com a mochila de um dos caçadores que sumiram, caída no chão. Ao lado dela, uma marca estranha no chão, como se algo pesado tivesse sido arrastado para dentro do mato. A floresta não está vazia, ela apenas está à espreita, e a névoa esconde algo mais do que apenas árvores e sombras.", "forest", "woods", 1, false),
                new StoryBlock(3, "Encontro 2", "A trilha se abre um pouco, e a névoa, por um momento, dá uma trégua. Vocês chegam num riacho de águas cristalinas que serpentia por entre raízes e pedras com musgo. A beleza do local contrasta com o ar pesado da floresta, e o murmúrio suave da água é um alívio. No entanto, vocês notam algo estranho: alguns peixes flutuam mortos, e a água, apesar de clara, parece ter um brilho leitoso, como se estivesse doente. A tensão está no ar, e um uivo distante ecoa entre as árvores. Vocês ouvem um movimento na água e percebem que algo se esconde nas margens, pronto para atacar", "forest", "woods", 2, false),
                new StoryBlock(4, "Ponto de Descanso", "A batalha nas margens do riacho termina, e a brisa suave do entardecer sopra a névoa para longe temporariamente. A beleza natural do lugar, com o som da água correndo e o canto distante dos pássaros, oferece um refúgio sereno. Vocês podem acampar, afiar suas armas, cuidar dos machucados e se preparar para a jornada pela trilha sinuosa que se aproxima.", "forest", "", 3, false),
                new StoryBlock(5, "Encontro 3", "O sol vai embora e pinta o céu com tons alaranjados e roxos que mal conseguem furar o manto da névoa que se adensa novamente. A trilha à sua frente se torna sinuosa, e as árvores parecem se fechar sobre vocês, suas copas retorcidas se transformando em dedos fantasmagóricos. O ar fica mais gelado, e a tensão aumenta. A névoa parece voltar mais forte. Vocês notam que alguns galhos parecem ter sido quebrados à força, e no chão, a grama está pisoteada. Não parece ser um caminho de animais, mas de algo grande e pesado que foi arrastado por ali.", "forest", "woods", 3, false),
                new StoryBlock(6, "Encontro 4", "A floresta some do nada, e vocês chegam num campo enorme coberto de pedras e escombros, como se uma cidade inteira tivesse sido esmagada e largada ali. A névoa por aqui é mais escura, quase cinzenta, e tem um cheiro forte de pedra fria e poeira milenar. A luz pálida da lua ilumina as colunas quebradas e as estátuas caídas de uma civilização élfica antiga. As ruínas, que antes eram grandiosas, agora parecem esqueletos de pedra, e vocês sentem que algo se move entre os vestígios da história, observando cada passo.", "cave", "caves", 4, false),
                new StoryBlock(7, "Ponto de Descanso", "Após a batalha, a névoa das ruínas desaparece, revelando uma vista para um lago tranquilo e prateado à luz da lua. O pátio em que vocês estão oferece um refúgio seguro, onde podem fazer uma fogueira e descansar, sentindo a brisa fresca que vem da água. É um momento de calmaria para se reequiparem e discutirem o que o espera na parte mais profunda das ruínas.", "cave", "", 5, false),
                new StoryBlock(8, "Encontro 5", "A noite é total nas ruínas. O vento frio assobia entre as colunas quebradas, e cada eco parece carregar os sussurros de almas perdidas. Não são vozes aleatórias, mas sim fragmentos de tristeza e desespero de um povo que já foi grande, lamentando seu destino. As ruínas, mal-assombradas, parecem mais um labirinto fantasma do que um lugar físico. Um som metálico, como o ranger de uma máquina antiga, ecoa ao longe. A cada passo, a sensação de que não estão sozinhos só aumenta, como se estivessem caminhando no meio de uma batalha que aconteceu há séculos, mas que nunca terminou.", "cave", "caves", 5, false),           
                new StoryBlock(9, "Encontro 6", "O amanhecer traz uma luz fraca. Vocês chegam ao que parece ser o pátio central das ruínas. A névoa se dissipa levemente, e vocês veem a entrada de uma tumba élfica, imponente e coberta de musgo. Um cheiro de terra molhada e mofo se torna forte.", "cave", "caves", 6, false),                      
                new StoryBlock(10, "Ponto de Descanso", "Depois de atravessar as ruínas, vocês dão de cara com o imponente pátio da tumba élfica. A névoa parece temer este lugar, dissipando-se em uma brisa suave que carrega o cheiro de pedra antiga e musgo. Entre as estátuas caídas e arcos rachados, há um local abrigado e silencioso. É um momento de calmaria antes da tempestade, onde vocês podem recarregar as energias, planejar a estratégia e preparar o espírito para a escuridão que os aguarda lá dentro.", "cave", "", 7, false),
                new StoryBlock(11, "Encontro 7", "A porta da tumba se abre com um rangido assustador. Uma escuridão profunda os recebe. Vocês se veem em um corredor estreito e úmido, iluminado apenas por suas tochas ou fontes de luz. A voz de um dos jogadores ecoa nos seus pensamentos: 'A maldição não é do mundo exterior. É do que está lá dentro.'", "cave", "undead", 7, false),                      
                new StoryBlock(12, "Encontro 8", "Vocês se aprofundam na tumba, passando por corredores sinuosos e úmidos. As paredes estão cobertas de símbolos élficos que parecem se mover e tremer à luz bruxuleante. O ar é denso, e o silêncio é quebrado apenas por gotas d'água caindo. Vocês percebem que não estão sozinhos nas profundezas escuras.", "cave", "undead", 8, false),                      
                new StoryBlock(13, "Ponto de Descanso", "Vocês encontram uma pequena câmara lateral, com runas mágicas brilhando nas paredes. A magia élfica ainda presente no local parece repelir a névoa da maldição, criando uma bolha de ar fresco e tranquilo. Este é o último refúgio antes do confronto final. É a chance de curar as feridas, afiar as lâminas e se preparar para o que os espera na câmara mais profunda.", "cave", "", 9, false),
                new StoryBlock(14, "Encontro 9", "Vocês se aproximam da câmara final. A névoa volta, mas com uma cor preta e espessa. Ela se move e se contorce, como se estivesse viva. O ar fica gelado, e a sensação de morte é avassaladora. De repente, a névoa ganha forma, e criaturas esqueléticas e espectrais emergem das sombras.", "cave", "undead", 9, false),
                new StoryBlock(15, "Ponto de Descanso", "A batalha na câmara final deixa um rastro de névoa negra e sombras. No chão, um círculo mágico de cura se ilumina, brilhando com uma luz dourada e suave que afasta o frio da morte. Ele foi ativado pela derrota das criaturas amaldiçoadas e oferece uma última oportunidade para curar suas feridas, afiar suas lâminas e se fortalecerem para o confronto decisivo. É o ponto de não-retorno, a última chance de respirar fundo antes de enfrentar a fonte da maldição.", "cave", "", 10, false),
                new StoryBlock(16, "Ato Final", "Vocês adentram a câmara final. O espaço se expande em uma vasta caverna subterrânea, o ar incrivelmente pesado e carregado de uma energia sinistra. No centro, um cristal negro do tamanho de um homem adulto pulsa com uma luz opaca e maligna, como um coração doente bombeando escuridão para toda a floresta. A névoa negra que assola a superfície aqui é densa como um manto, girando ao redor do cristal e se estendendo em tentáculos sombrios pelas paredes da caverna. O chão é feito de pedra irregular, coberto por uma fina camada de poeira e fragmentos de ossos antigos. Runas élficas corrompidas brilham fracamente nas paredes, pulsando em sincronia com o cristal, como se estivessem aprisionando ou alimentando sua energia. Um frio intenso emana do cristal, penetrando suas roupas e congelando a respiração em seus pulmões. Diante do cristal, paira uma figura esquelética, envolta em mantos élficos esfarrapados que já foram majestosos, mas agora estão gastos e manchados pela corrupção. Em suas mãos ossudas, ele segura um cajado retorcido, feito de madeira escura e adornado com fragmentos do mesmo cristal negro. Olhos vermelhos e vazios fitam vocês, carregados de uma maldade antiga e de um poder que corrompeu toda a floresta. A fonte da maldição da Floresta Sussurrante finalmente se revela.", "cave", "undead", 10, true),
                new StoryBlock(17, "O Silêncio Após a Névoa", "O cristal negro estala uma última vez. As runas élficas corrompidas nas paredes piscam de forma errática e, então, se apagam. Um som grave e profundo ecoa pela caverna, como um suspiro antigo sendo finalmente libertado. A figura esquelética diante de vocês se desfaz em poeira acinzentada, levada por uma corrente de ar frio que percorre toda a tumba. O cristal, agora rachado, perde o brilho sombrio e se parte em fragmentos inertes, espalhando-se pelo chão como vidro morto.\n\nA névoa negra começa a recuar. Primeiro dentro da caverna, depois pelos corredores da tumba, como se estivesse sendo puxada de volta para um lugar que não deveria mais existir. O ar fica mais leve, e pela primeira vez desde que entraram na floresta, vocês respiram sem sentir o peso da maldição nos pulmões.\n\nAo retornarem à superfície, o amanhecer rompe as copas das árvores. A Floresta Sussurrante está diferente. A névoa desapareceu quase por completo, os galhos retorcidos parecem menos ameaçadores, e o canto tímido de pássaros ecoa entre as árvores. O silêncio opressor foi substituído por um murmúrio natural de vida retomando seu espaço.\n\nDe volta à vila de Pedraverde, Helga os recebe em silêncio, observando o céu limpo com os olhos marejados. 'Então… acabou', ela diz, com um misto de alívio e incredulidade. Os moradores saem de suas casas, ainda desconfiados, mas aos poucos a esperança toma conta do lugar. Vocês não são recebidos apenas como mercenários ou aventureiros, mas como aqueles que enfrentaram uma maldição antiga e devolveram o futuro à vila.\n\nEmbora a floresta nunca esqueça completamente o que aconteceu, a fonte da corrupção foi destruída. As ruínas élficas permanecem como um lembrete silencioso do preço da arrogância e da magia mal utilizada. E vocês seguem viagem, sabendo que deixaram para trás um lugar marcado pela escuridão… mas também pela redenção.", "village", "", 10, false)
            ]
        ),
        new Story(2, "A Cidade Onde Ninguém Dorme", "ash", 
            [
                new StoryBlock(1, "Prólogo", "A metrópole medieval de Nova Vigília é tão imensa quanto antiga. Foi erguida sobre ruínas esquecidas, governada por conselhos corruptos e sustentada por guildas que valem mais que reis. Aqui, ninguém dorme, os nobres tramam atrás de portas de carvalho, o povo sussurra conspirando, sombras caminham sozinhas, e todos têm um preço, mesmo quando juram que não. Na última lua cheia, um assassinato abalou o equilíbrio de poder. E todas as evidências — cuidadosamente plantadas — apontam para vocês, por isso cidade inteira se move contra o grupo. Quem foi assassinado foi um aliado de vocês, com grande influência politica, chamado Jorn Mereth, que curiosamente, tinha uma reunião com o grupo antes de ser assassinado. Ninguém sabe ao certo o motivo do assassinato, será o trabalho de vocês descobrir quem o matou e porque.", "city", "", 1, false),
                new StoryBlock(2, "Encontro 1", "As ruas apertadas do Distrito Velho cheiram a caldo quente, carvão molhado e metal oxidado. Lamparinas oscilam, presas por cordas improvisadas que cruzam os becos como teias de aranha. Velhas casas de madeira rangem sob o próprio peso. Moradores trancam portas ao ver vocês como se já soubessem de algo. Enquanto investigam o local do assassinato, percebem: pegadas apagadas com areia úmida; marcas de sangue que alguém tentou limpar às pressas; uma janela quebrada… por dentro; símbolos riscados na parede, como se alguém tivesse deixado uma mensagem oculta. Enquanto procuram por pistas, capangas da Guilda do Punho Sórdido cercam vocês. Eles não querem brigar… Eles querem garantir que vocês não saiam dali vivos. Um dos capangas hesita ao ver o grupo, talvez reconheceu vocês?", "city", "ruins", 1, false),
                new StoryBlock(3, "Pós-encontro", "Quando a batalha chega ao fim, uma figure ilustre aparece a vocês. Era Alaric, mais conhecido como “Mãos de Fuligem”. Vocês percebem que há medo em sua voz, porém, mesmo hesitante ele revela que viu quem adulterou a cena do crime. “Vi um arqueiro mascarado, pouco antes de vocês chegarem, ele estava tentando apagar os vestígios do assassinato. Porém, saiu as pressas quando viu vocês chegando e acabou derrubando isso” - Disse Alaric enquanto entregava um medalhão com um símbolo desconhecido à vocês. Após isso, vocês seguem sua jornada em direção a Estrada Alta.", "city", "", 2, false),
                new StoryBlock(4, "Encontro 2", "A Estrada Alta é uma ponte colossal que atravessa telhados como o dorso de uma serpente de pedra. O vento sopra forte, arrastando poeira e folhas secas. Carroças quebradas e esqueletos de mercadorias roubadas fazem do caminho uma galeria de crimes antigos. Dentro de um baú escondido sob tábuas soltas, vocês acham um pergaminho com selos falsificados do Conselho — uma prova que poderia inocentá-los. Assim que o tocam, uma milícia urbana os intercepta. Eles sabiam exatamente onde e quando vocês estariam ali.", "city", "ruins", 2, false),
                new StoryBlock(5, "Pós-encontro", "Após terminarem a batalha, vocês percebem que o líder da milícia carrega um anel com o mesmo símbolo do medalhão encontrado no Distrito Velho, porém, já morto, é impossível saber qual a ligação entre os dois. Vocês veem alguém vindo correndo de longe, ele chega ofegante até vocês. Eis um velho amigo Sir Valen Dorrin. Ele é um cavaleiro que patrulha a cidade e viu à distância toda a movimentação que aconteceu na ponte, porém, demorou demais para chegar e a batalha se encerrou. “O que é isso que vocês encontraram?” - Pergunta Dorrin ao ver o pergaminho. Ao explicarem, ele diz: “Vocês devem levar isso ao Conselho imediatamente, no ponto mais alto da cidade!", "city", "", 3, false),
                new StoryBlock(6, "Ponto de Descanso", "Abaixo da ponte antiga despensa de mercadores oferece palha seca, abrigo da chuva e silêncio desconfortável. Vocês descansam… mas sentem como se estivessem sendo observados.", "city", "", 3, false),
                new StoryBlock(7, "Encontro 3", "Após descansados, vocês seguem sua jornada para além da ponte e chegam no Bairro dos Magistrados. Este é o coração da nobreza. Palácios com colunas de mármore; Guardas com armaduras polidas; Estátuas que observam cada passo; Bandeiras pesadas com brasões de cada uma das nobres familias. Enquanto caminham pelas ruas desertas, vocês percebem janelas se fechando, portas batendo, como se ninguém quisesse a presença de vocês por ali. Um pouco mais a frente, vocês se deparam com o Arquivo Real, um local de historiadores, onde ficam armazenados todos arquivos oficiais do Conselho. Ao entrar se deparam com um labirinto de pergaminhos, degraus e poeira dourada. Ao iniciarem suas buscas por uma nova pista, vocês são surpreendidos por mercenários descem pelos vitrais como pássaros de ferro. Eles estão aqui para garantir que vocês não deixem esse lugar com vida.", "tower", "ruins", 3, false),
                new StoryBlock(8, "Pós-encontro", "Após a batalha um dos mercenários permanece vivo. E um de vocês tem a brilhante ideia de interroga-lo, porém, ao caminharem em sua direção, percebem que uma fumaça verde sai de sua boca. Ele havia se envenenado… Vocês assistem aquele pobre homem se contorcer até a morte enquanto dizia repetidamente: “Serei iluminado!” — O que isso significava? No final das contas, não havia nada do interesse de vocês dentro do Arquivo Real. Sendo assim, vocês seguem em frente.", "tower", "", 4, false),
                new StoryBlock(9, "Encontro 4", "O Mercado Clandestino é um caos organizado por criminosos. Tendas coloridas, Contrabandistas gritando preços, Gaiolas com criaturas estranhas, Perfumes fortes misturados a suor e ferrugem. A guilda de informantes local possui a chave da próxima pista. Mas antes que falem, um esquadrão mascarado invade o mercado: barracas voam, poeira sobe, pessoas fogem gritando e há brilho de lâminas por toda parte. É um tumulto calculado e proposital.", "city", "ruins", 4, false),
                new StoryBlock(10, "Pós-encontro", "Um informante moribundo segura a mão de um dos jogadores e sussurra: 'Traídos… desde o início…'. Após eliminarem os inimigos, vocês auxiliam os mercadores a levantarem suas tendas novamente. Vocês gastam boas horas auxiliando aquelas pessoas para que tudo volte à normalidade. Enquanto estão lá, algumas pessoas da Guilda de Mercadores observam. Ao terminarem, a Guilda chega até vocês e agradece pelos serviços, oferecendo um local de abrigo para descanso.", "city", "", 5, false),
                new StoryBlock(11, "Ponto de Descanso", "A Guilda os leva a um abrigo subterrâneo com: água potável; esteiras de palha fina; arqueiros ocultos protegendo vocês; Após o descanso, os mercadores novamente e agradecem e dão à vocês uma recompensa (Cada aventureiro pode abrir mais um baú). E direcionam vocês até a entrada de Tuneis antigos da cidade.", "city", "", 5, false),
                new StoryBlock(12, "Encontro 5", "Túneis ancestrais servem como o esgoto e o submundo da metrópole. símbolos antigos, goteiras constantes, rachaduras no teto, inscrições apagadas por tempo ou medo. Um comboio clandestino surge, puxando vagonetes improvisados carregados de assassinos encapuzados. Eles avançam rápido demais. Rápido demais para um ataque improvisado. Isso foi planejado.", "citytunnels", "ruins", 5, false),
                new StoryBlock(13, "Pós-encontro", "Aqui já está claro pra vocês que tem alguém delatando todos os seus movimentos para seus inimigos. Parece que estão sempre um passo a frente vocês, planejando cuidadosamente cada um dos ataques. Os herois então passam ali alguns minutos pensando em quem poderia estar fazendo algo assim. Mas são surpreendidos por sons de passos. Todo som nesses tuneis ecoa, fazendo com que os passos sejam ouvidos de muito longe. Uma figura vem se aproximando até vocês no escuro e vocês passam a ouvir algo como um murmúrio, como uma reza. É Teren Halvar um religioso, que vive dentro dos túneis. Tem como missão de vida purificar esses túneis de presenças malignas. “O que fazem aqui?” - Diz Halvar com um tom de incômodo - “Há uma saída no fim deste tunel. Lá vocês vão encontrar uma passagem para as forjas, vão para lá antes que encontrem aqui algo pior do que humanos mascarados.” Então quietos, vocês seguem na direção que Halvar aponta. E ele segue murmurando corredor a dentro.", "citytunnels", "", 6, false),
                new StoryBlock(14, "Encontro 6", "Um enorme complexo de forjas que foram desligadas recentemente, toda a operação de forja foi migrado para o setor sul da cidade! Aqui há somente: martelos quebrados, fornos frios e restos do que um dia foi uma grande produção de armas e armaduras. Em meio ao caos, vocês encontram um local muito arrumado para estar abandonado. Uma fogueira ainda acesa revela que havia alguém ali até pouco tempo atrás. Vocês encontram uma série de livros e pergaminhos em cima de uma mesa. Diversos dos documentos usam um nome que intriga vocês. Os Invisíveis, o que seria isso? Não muito tempo depois, um dos livros revela a verdade.A existência dos Invisíveis, uma aristocracia mascarada que manipula a cidade há séculos. Eles controlam: impostos; julgamentos; eleições; execuções; Quando todos estavam distraídos, os donos daquele posto retornam e se surpreendem ao verem vocês revirando todas as coisas e já se preparam para o ataque!", "forge", "ruins", 6, false),
                new StoryBlock(15, "Pós-encontro", "Após a batalha, vocês reviram o corpo dos mortos e encontram um mapa das forjas com uma marcação em uma parede não muito distante de onde vocês estão!", "forge", "", 7, false),
                new StoryBlock(16, "Ponto de Descanso", "Após a batalha, vocês encontram um dormitório pertencente aos antigos trabalhadores da forja. Lá vocês encontram camas, lareiras e uma porta com tranca. Vocês trancam a porta e aproveitam para descansar por um momento. Ao saírem, vocês vão direto na parede marcada no mapa, lá, vocês encontram uma espécie de passagem escondida com um corredor interminável.", "forge", "", 7, false),
                new StoryBlock(17, "Encontro 7", "A passagem secreta das forjas leva a uma longa escadaria que termina em um jardim morto, escondido no meio de um morro central da cidade. Nenhum mapa registra esse lugar — mas o portão de ferro ali está, enferrujado, porém intacto. A mansão à frente parece respirar. janelas compridas como olhos vigiando vocês; tapeçarias antigas movendo-se apesar da ausência de vento; cheiro de vela, poeira e incenso queimado há dias. Ao entrarem, percebem que não há servos. A casa inteira parece ter sido abandonada pelos vivos… Mas não pelo poder. Corredores longos exibem retratos de aristocratas usando máscaras de ferro, todos olhando fixamente para quem passa. O silêncio é sufocante — até que vocês o quebram, mexendo em uma porta trancada. E é aí que os inimigos aparecem.", "mansion", "ruins", 7, false),
                new StoryBlock(18, "Pós-encontro", "Enquanto exploram a mansão, uma porta secreta se abre. De lá saí uma mulher alta e magra, com roupas simples demais para aquele lugar, vocês percebem que ela está completamente ferida, mas não são feridas comuns, parecem feridas causadas por tortura. Tudo indica que ela é uma serviçal naquele lugar. Ela chega em completo silêncio, e anda até vocês. Então, entrega a vocês um pequeno pergaminho dobrado. Nele, está escrito: 'Meu nome é Seris Althunn, estou aprisionada aqui a 15 anos, peço a ajuda de vocês, matem meu mestre e me libertem por favor! Lá está a entrada para o Salão dos Pactos… vocês precisam ir'. Ela aponta para uma passagem que leva ao subsolo da mansão, então, ela volta novamente em silêncio para a passagem de onde saiu e a passagem se fecha novamente.", "mansion", "", 8, false),
                new StoryBlock(19, "Encontro 8", "O Salão dos Pactos é enorme, circular, com seis pilares grossos de pedra e uma mesa circular de mármore no centro. Em cada parede há prateleiras lotadas de pergaminhos selados — contratos políticos, dívidas antigas, acusações, alianças secretas. No centro, três figuras mascaradas os aguardam. Os Interrogadores Mascarados. Executores dos Invisíveis. Eles falam em uníssono: 'Vocês chegaram longe demais.', 'Mas eis que oferecemos um acordo.', 'Se sobreviverem, revelamos a verdade.'", "mansion", "ruins", 8, false),
                new StoryBlock(20, "Pós-encontro", "'Valen Dorrin é quem vocês estão procurando.' - Dizem os executores antes de virarem pó. Vocês ficam confusos, pois esse nome é de alguém conhecido e um antigo amigo. O que querem dizer com isso?", "mansion", "", 9, false),
                new StoryBlock(21, "Ponto de Descanso", "Um arquivo trancado serve como refúgio. É um lugar onde vocês se sentem completamente inseguros, aqui, vocês podem executar somente uma ação.", "mansion", "", 9, false),
                new StoryBlock(22, "Encontro 9", "A Câmara do Conselho Oculto é silenciosa demais. O som dos passos ecoa como se a própria sala respirasse. Seis tronos de madeira escura se alinham ao redor de vocês. Cinco estão vazios. O sexto, no fundo da sala, está ocupado. Mas não por uma figura mascarada. Por registros de pergaminhos deixados abertos sobre o trono. Quando vocês se aproximam, percebem algo perturbador: Cada página documenta um dos seus passos na investigação. Datas, horas, descrições… até pensamentos que vocês tiveram em voz baixa. Vocês não estavam investigando o caso. Vocês eram o caso. De repente, uma voz demoniaca ecoa atrás dos tronos: 'Como chegaram até aqui? Vocês deveriam ter sido mortos por traição. Todo meu esforço para incriminar vocês foi em vão? Terei que encontrar outras pessoas para culpar, pois vocês morrem aqui.' O Conselheiro Mascarado surge das sombras, segurando uma máscara rachada. Então estala os dedos. As sombras dos cinco tronos vazios ganham forma, cada uma moldada em um espectro armado (Todos os monstros da rodada tem +2 de ataque).", "mansion", "ruins", 9, false),
                new StoryBlock(23, "Pós-encontro", "Durante o combate, o Conselheiro observou, sem interferir, como se estivesse avaliando-os pela última vez. Antes de desaparecer em fumaça, ele deixa cair uma última página do registro. Nela, em letras fortes, está escrito: 'Projeto Dorrin — Conclusão iminente.'", "mansion", "", 10, false),
                new StoryBlock(24, "Ponto de Descanso", "Uma vez que o conselheiro se vai, toda a pressão que estavam sentido se vai. Agora a própria Câmara serve como descanso pra vocês. Vocês sentam, conversam e se preparam para o que está por vir.", "mansion", "", 10, false),
                new StoryBlock(25, "Encontro 10", "O topo da torre os leva ao Tribunal dos Traidores , um lugar açoitado por ventos cortantes. As rajadas de vento são tão fortes que empurram e parecem rasgar a pele, como se vidro estivesse misturado ao vento. O local é feito de colunas partidas e desenhos arcanos manchados de sangue velho. Há também uma arquibancada ao fundo e um trono centralizado, com duas grandes estátuas dos Invisíveis ao lado do trono. No centro, sentado no trono está Valen Dorrin. Seu olhar é tranquilo. Não parece assustado, não parece ter medo, mas parece completamente confortável. Ele ergue o rosto, deixando a chuva escorrer por ele. 'Essa cidade é controlada por nós. Mesmo que levassem o pergaminho ao conselho, de nada adiantaria, pois nós somos o Conselho. Vocês estavam fadados a morte desde o inicio. Mas antes de morrerem, quero que vocês presenciem minha ascensão'. Neste instânte as tochas se apagam uma a uma. O vento se cala. Então, Valen se levanta dizendo já com uma voz demoniaca: 'Jorn Mereth precisou morrer, ele descobriu algo que não devia e foi correndo contar a vocês, então foi necessário silencia-lo.'. A luz ao redor dele distorce, como se ele fosse uma fonte de escuridão. As veias brilham como lâminas. A pele se abre como papel queimado. Asas surgem em suas costas. Não é mais possível reconhece-lo. Demonios que antes pra vocês eram apenas contos e fantasia, agora parecem mais verdadeiros do que nunca, havia um na frente de vocês, pronto para tirar suas vidas. Valen Dorrin não era corrompido. Ele sempre foi isso. A batalha final começou. E agora… não é por honra, nem por glória, nem por absolvição. É por sobrevivência.", "towertop", "ruins", 10, true),
                new StoryBlock(26, "A Vitória", "Após derrotado, Valen é incendiado por chamas que o consomem. Pouco a pouco seu corpo é transformado em cinzas e levado pelos ventos fortes da torre. A chuva cessa e o sol começa a nascer no horizonte. Um novo conselho deve ser estabelecido para que a ordem na cidade seja mantida. Daqui em diante, nossos herois vão trabalhar imensamente, para que esse novo conselho seja completamente integro. Se certificando de que nenhuma organização das sombras tenha controle e poder novamente.", "towertop", "", 10, false)
            ]
        )
    ];
}