import { BoardNode, StoryBoard } from '../board';

/**
 * Tabuleiro de "A Maldição da Floresta Sussurrante".
 * Layout dos nodes desenhado em tools/node-map-preview (coordenadas na arte de 2000x1115).
 * monsterType: woods = vila/floresta/lago/trilha sul; ruins = muralhas externas;
 * undead = cripta e corredor dos nichos; caves = caverna inferior.
 */
const nodes: BoardNode[] = [
        { id: 'S01', map: 'sup', x: 330, y: 880, type: 'start', monsterType: '', level: 0, next: ['S01~1'] },
        { id: 'S02', map: 'sup', x: 400, y: 830, type: 'battle', monsterType: 'woods', level: 1, next: ['S03'] },
        { id: 'S03', map: 'sup', x: 450, y: 790, type: 'fork', monsterType: '', level: 0, next: ['SS1','N01'], labels: {"SS1":"Margem sul — curta","N01":"Contornar o lago pelo norte — longa, com baú"} },
        { id: 'SS1', map: 'sup', x: 540, y: 775, type: 'battle', monsterType: 'woods', level: 2, next: ['SS1~1'] },
        { id: 'SS2', map: 'sup', x: 650, y: 740, type: 'battle', monsterType: 'woods', level: 2, next: ['SS2~1'] },
        { id: 'SS3', map: 'sup', x: 760, y: 700, type: 'battle', monsterType: 'woods', level: 2, next: ['SS3~1'] },
        { id: 'SS4', map: 'sup', x: 850, y: 650, type: 'battle', monsterType: 'woods', level: 3, next: ['SS4~1'] },
        { id: 'N01', map: 'sup', x: 400, y: 720, type: 'battle', monsterType: 'woods', level: 2, next: ['N01~1'] },
        { id: 'N02', map: 'sup', x: 350, y: 640, type: 'battle', monsterType: 'woods', level: 2, next: ['N03'] },
        { id: 'N03', map: 'sup', x: 330, y: 560, type: 'battle', monsterType: 'woods', level: 2, next: ['N03~1'] },
        { id: 'N04', map: 'sup', x: 390, y: 490, type: 'battle', monsterType: 'woods', level: 2, next: ['N04~1'] },
        { id: 'N05', map: 'sup', x: 470, y: 430, type: 'rest', monsterType: '', level: 0, next: ['N05~1'] },
        { id: 'N06', map: 'sup', x: 570, y: 400, type: 'battle', monsterType: 'woods', level: 3, next: ['N06~1'] },
        { id: 'N07', map: 'sup', x: 680, y: 390, type: 'battle', monsterType: 'woods', level: 3, next: ['N07~1'] },
        { id: 'N08', map: 'sup', x: 780, y: 410, type: 'battle', monsterType: 'woods', level: 4, next: ['N08~1'] },
        { id: 'N09', map: 'sup', x: 860, y: 465, type: 'battle', monsterType: 'woods', level: 4, next: ['N10'] },
        { id: 'N10', map: 'sup', x: 900, y: 530, type: 'reward', monsterType: '', level: 0, next: ['M01'] },
        { id: 'M01', map: 'sup', x: 935, y: 605, type: 'rest', monsterType: '', level: 0, next: ['M01~1'] },
        { id: 'E01', map: 'sup', x: 965, y: 700, type: 'battle', monsterType: 'ruins', level: 3, next: ['E01~1'] },
        { id: 'E02', map: 'sup', x: 1030, y: 765, type: 'battle', monsterType: 'ruins', level: 4, next: ['E02~1'] },
        { id: 'E03', map: 'sup', x: 1125, y: 815, type: 'battle', monsterType: 'ruins', level: 4, next: ['E03~1'] },
        { id: 'E04', map: 'sup', x: 1235, y: 850, type: 'battle', monsterType: 'ruins', level: 5, next: ['E04~1'] },
        { id: 'E05', map: 'sup', x: 1325, y: 865, type: 'battle', monsterType: 'ruins', level: 5, next: ['E06'] },
        { id: 'E06', map: 'sup', x: 1373, y: 863, type: 'fork', monsterType: '', level: 0, next: ['B01','T01'], labels: {"B01":"Subir pela brecha sul — direto","T01":"Descer a trilha sul até o baú — ida e volta"} },
        { id: 'B01', map: 'sup', x: 1365, y: 805, type: 'battle', monsterType: 'ruins', level: 5, next: ['B02'] },
        { id: 'B02', map: 'sup', x: 1348, y: 745, type: 'battle', monsterType: 'ruins', level: 5, next: ['B03'] },
        { id: 'B03', map: 'sup', x: 1340, y: 690, type: 'battle', monsterType: 'ruins', level: 6, next: ['B04'] },
        { id: 'B04', map: 'sup', x: 1332, y: 640, type: 'battle', monsterType: 'ruins', level: 6, next: ['G01'] },
        { id: 'T01', map: 'sup', x: 1379, y: 922, type: 'battle', monsterType: 'woods', level: 5, next: ['T02'] },
        { id: 'T02', map: 'sup', x: 1382, y: 970, type: 'battle', monsterType: 'woods', level: 5, next: ['T03'] },
        { id: 'T03', map: 'sup', x: 1379, y: 1020, type: 'battle', monsterType: 'woods', level: 5, next: ['T04'] },
        { id: 'T04', map: 'sup', x: 1387, y: 1073, type: 'reward', monsterType: '', level: 0, next: ['T03r'] },
        { id: 'T03r', map: 'sup', x: 1418, y: 1020, type: 'battle', monsterType: 'woods', level: 5, next: ['T02r'] },
        { id: 'T02r', map: 'sup', x: 1421, y: 961, type: 'rest', monsterType: '', level: 0, next: ['T01r'] },
        { id: 'T01r', map: 'sup', x: 1424, y: 916, type: 'battle', monsterType: 'woods', level: 6, next: ['T01r~1'] },
        { id: 'G01', map: 'sup', x: 1310, y: 600, type: 'gate', monsterType: '', level: 0, next: ['K01'] },
        { id: 'S01~1', map: 'sup', x: 365, y: 855, type: 'battle', monsterType: 'woods', level: 1, next: ['S02'] },
        { id: 'SS1~1', map: 'sup', x: 595, y: 758, type: 'battle', monsterType: 'woods', level: 2, next: ['SS2'] },
        { id: 'SS2~1', map: 'sup', x: 705, y: 720, type: 'battle', monsterType: 'woods', level: 2, next: ['SS3'] },
        { id: 'SS3~1', map: 'sup', x: 805, y: 675, type: 'battle', monsterType: 'woods', level: 3, next: ['SS4'] },
        { id: 'SS4~1', map: 'sup', x: 893, y: 628, type: 'battle', monsterType: 'woods', level: 3, next: ['M01'] },
        { id: 'N01~1', map: 'sup', x: 375, y: 680, type: 'battle', monsterType: 'woods', level: 2, next: ['N02'] },
        { id: 'N03~1', map: 'sup', x: 360, y: 525, type: 'battle', monsterType: 'woods', level: 2, next: ['N04'] },
        { id: 'N04~1', map: 'sup', x: 430, y: 460, type: 'battle', monsterType: 'woods', level: 3, next: ['N05'] },
        { id: 'N05~1', map: 'sup', x: 520, y: 415, type: 'battle', monsterType: 'woods', level: 3, next: ['N06'] },
        { id: 'N06~1', map: 'sup', x: 625, y: 395, type: 'battle', monsterType: 'woods', level: 3, next: ['N07'] },
        { id: 'N07~1', map: 'sup', x: 730, y: 400, type: 'battle', monsterType: 'woods', level: 3, next: ['N08'] },
        { id: 'N08~1', map: 'sup', x: 820, y: 438, type: 'battle', monsterType: 'woods', level: 4, next: ['N09'] },
        { id: 'M01~1', map: 'sup', x: 950, y: 653, type: 'battle', monsterType: 'ruins', level: 3, next: ['E01'] },
        { id: 'E01~1', map: 'sup', x: 998, y: 733, type: 'battle', monsterType: 'ruins', level: 4, next: ['E02'] },
        { id: 'E02~1', map: 'sup', x: 1078, y: 790, type: 'battle', monsterType: 'ruins', level: 4, next: ['E03'] },
        { id: 'E03~1', map: 'sup', x: 1180, y: 833, type: 'battle', monsterType: 'ruins', level: 4, next: ['E04'] },
        { id: 'E04~1', map: 'sup', x: 1280, y: 858, type: 'battle', monsterType: 'ruins', level: 5, next: ['E05'] },
        { id: 'T01r~1', map: 'sup', x: 1395, y: 861, type: 'battle', monsterType: 'woods', level: 6, next: ['B01'] },
        { id: 'K01', map: 'tomb', x: 210, y: 400, type: 'start', monsterType: '', level: 0, next: ['K02'] },
        { id: 'K02', map: 'tomb', x: 330, y: 400, type: 'battle', monsterType: 'undead', level: 6, next: ['K02~1'] },
        { id: 'K03', map: 'tomb', x: 450, y: 460, type: 'battle', monsterType: 'undead', level: 7, next: ['K04'] },
        { id: 'K04', map: 'tomb', x: 560, y: 520, type: 'battle', monsterType: 'undead', level: 7, next: ['K04~1'] },
        { id: 'K05', map: 'tomb', x: 690, y: 570, type: 'battle', monsterType: 'undead', level: 7, next: ['K05~1'] },
        { id: 'KF', map: 'tomb', x: 840, y: 650, type: 'fork', monsterType: '', level: 0, next: ['U01','L01'], labels: {"U01":"Corredor dos nichos — curto","L01":"Caverna inferior — longa, com baú"} },
        { id: 'U01', map: 'tomb', x: 940, y: 540, type: 'battle', monsterType: 'undead', level: 8, next: ['U01~1'] },
        { id: 'U02', map: 'tomb', x: 1070, y: 480, type: 'battle', monsterType: 'undead', level: 8, next: ['U02~1'] },
        { id: 'U03', map: 'tomb', x: 1200, y: 430, type: 'battle', monsterType: 'undead', level: 8, next: ['U03~1'] },
        { id: 'U04', map: 'tomb', x: 1330, y: 340, type: 'battle', monsterType: 'undead', level: 9, next: ['U04~1'] },
        { id: 'U05', map: 'tomb', x: 1450, y: 270, type: 'battle', monsterType: 'undead', level: 9, next: ['U05~1'] },
        { id: 'L01', map: 'tomb', x: 890, y: 760, type: 'battle', monsterType: 'caves', level: 7, next: ['L01~1'] },
        { id: 'L02', map: 'tomb', x: 960, y: 880, type: 'battle', monsterType: 'caves', level: 7, next: ['L02~1'] },
        { id: 'L03', map: 'tomb', x: 1080, y: 970, type: 'battle', monsterType: 'caves', level: 7, next: ['L03~1'] },
        { id: 'L04', map: 'tomb', x: 1250, y: 1000, type: 'battle', monsterType: 'caves', level: 8, next: ['L04~1'] },
        { id: 'L05', map: 'tomb', x: 1450, y: 985, type: 'rest', monsterType: '', level: 0, next: ['L05~1'] },
        { id: 'L06', map: 'tomb', x: 1620, y: 940, type: 'battle', monsterType: 'caves', level: 8, next: ['L06~1'] },
        { id: 'L07', map: 'tomb', x: 1780, y: 860, type: 'reward', monsterType: '', level: 0, next: ['L07~1'] },
        { id: 'L08', map: 'tomb', x: 1890, y: 740, type: 'battle', monsterType: 'caves', level: 9, next: ['L08~1'] },
        { id: 'L09', map: 'tomb', x: 1790, y: 640, type: 'battle', monsterType: 'caves', level: 9, next: ['L09~1'] },
        { id: 'L10', map: 'tomb', x: 1690, y: 545, type: 'battle', monsterType: 'caves', level: 10, next: ['M02'] },
        { id: 'M02', map: 'tomb', x: 1620, y: 440, type: 'rest', monsterType: '', level: 0, next: ['M02~1'] },
        { id: 'BOSS', map: 'tomb', x: 1735, y: 320, type: 'boss', monsterType: 'undead', level: 10, next: [] },
        { id: 'K02~1', map: 'tomb', x: 390, y: 430, type: 'battle', monsterType: 'undead', level: 6, next: ['K03'] },
        { id: 'K04~1', map: 'tomb', x: 625, y: 545, type: 'battle', monsterType: 'undead', level: 7, next: ['K05'] },
        { id: 'K05~1', map: 'tomb', x: 765, y: 610, type: 'battle', monsterType: 'undead', level: 7, next: ['KF'] },
        { id: 'U01~1', map: 'tomb', x: 1005, y: 510, type: 'battle', monsterType: 'undead', level: 8, next: ['U02'] },
        { id: 'U02~1', map: 'tomb', x: 1135, y: 455, type: 'battle', monsterType: 'undead', level: 8, next: ['U03'] },
        { id: 'U03~1', map: 'tomb', x: 1265, y: 385, type: 'battle', monsterType: 'undead', level: 9, next: ['U04'] },
        { id: 'U04~1', map: 'tomb', x: 1390, y: 305, type: 'battle', monsterType: 'undead', level: 9, next: ['U05'] },
        { id: 'U05~1', map: 'tomb', x: 1507, y: 327, type: 'battle', monsterType: 'undead', level: 9, next: ['U05~2'] },
        { id: 'U05~2', map: 'tomb', x: 1563, y: 383, type: 'battle', monsterType: 'undead', level: 9, next: ['M02'] },
        { id: 'L01~1', map: 'tomb', x: 925, y: 820, type: 'battle', monsterType: 'caves', level: 7, next: ['L02'] },
        { id: 'L02~1', map: 'tomb', x: 1020, y: 925, type: 'battle', monsterType: 'caves', level: 7, next: ['L03'] },
        { id: 'L03~1', map: 'tomb', x: 1165, y: 985, type: 'battle', monsterType: 'caves', level: 8, next: ['L04'] },
        { id: 'L04~1', map: 'tomb', x: 1350, y: 993, type: 'battle', monsterType: 'caves', level: 8, next: ['L05'] },
        { id: 'L05~1', map: 'tomb', x: 1535, y: 963, type: 'battle', monsterType: 'caves', level: 8, next: ['L06'] },
        { id: 'L06~1', map: 'tomb', x: 1700, y: 900, type: 'battle', monsterType: 'caves', level: 8, next: ['L07'] },
        { id: 'L07~1', map: 'tomb', x: 1835, y: 800, type: 'battle', monsterType: 'caves', level: 9, next: ['L08'] },
        { id: 'L08~1', map: 'tomb', x: 1840, y: 690, type: 'battle', monsterType: 'caves', level: 9, next: ['L09'] },
        { id: 'L09~1', map: 'tomb', x: 1740, y: 593, type: 'battle', monsterType: 'caves', level: 9, next: ['L10'] },
        { id: 'M02~1', map: 'tomb', x: 1678, y: 380, type: 'battle', monsterType: 'undead', level: 10, next: ['BOSS'] },
];

export const whisperingForestBoard: StoryBoard = {
    maps: [
        { id: 'sup', image: '/assets/boards/whispering-forest/superficie.webp', width: 2000, height: 1115 },
        { id: 'tomb', image: '/assets/boards/whispering-forest/catacumbas.webp', width: 2000, height: 1115 }
    ],
    nodes,
    startNodeId: 'S01',
    bossId: 10003,
    intro: 'Vocês chegam a Pedraverde, vila à beira da Floresta Sussurrante. Uma névoa gelada e viva engole a mata, e os caçadores que entraram nela não foram mortos: foram mudados. Helga, a chefe da guarda, pede que sigam as trilhas, encontrem a tumba élfica de onde vem a maldição e a destruam antes que ela alcance a vila. Rolem o d6 e avancem pelo tabuleiro.',
    gateText: 'Diante do portão guardado por gárgulas, a névoa se adensa e se parte como uma cortina. Vocês descem às catacumbas élficas, onde o ar pesa e a escuridão parece respirar.',
    restText: 'Um refúgio seguro. Vocês podem descansar, cuidar dos ferimentos e se preparar para o que vem a seguir.',
    rewardText: 'Um tesouro! Cada aventureiro pode abrir mais um baú.',
    endText: 'O cristal negro estala uma última vez e as runas se apagam. A névoa recua e o amanhecer encontra uma Floresta Sussurrante enfim em paz. Em Pedraverde, Helga os recebe em silêncio: a maldição acabou.'
};
