import { BoardNode, StoryBoard } from '../board';

/**
 * Tabuleiro de "A Maldição da Floresta Sussurrante".
 * Layout dos nodes desenhado em tools/node-map-preview (coordenadas na arte de 2000x1115).
 * monsterType: woods = vila/floresta/lago/trilha sul; ruins = muralhas externas;
 * undead = cripta e corredor dos nichos; caves = caverna inferior.
 */
const nodes: BoardNode[] = [
        { id: 'S01', map: 'sup', x: 281, y: 809, type: 'start', monsterType: '', level: 0, next: ['S01~1'] },
        { id: 'A01', map: 'sup', x: 222, y: 764, type: 'safe', monsterType: '', level: 0, next: ['A02'] },
        { id: 'A02', map: 'sup', x: 176, y: 762, type: 'safe', monsterType: '', level: 0, next: ['A03'] },
        { id: 'A03', map: 'sup', x: 133, y: 776, type: 'safe', monsterType: '', level: 0, next: ['A04'] },
        { id: 'A04', map: 'sup', x: 105, y: 807, type: 'safe', monsterType: '', level: 0, next: ['A05'] },
        { id: 'A05', map: 'sup', x: 100, y: 847, type: 'safe', monsterType: '', level: 0, next: ['A06'] },
        { id: 'A06', map: 'sup', x: 119, y: 883, type: 'safe', monsterType: '', level: 0, next: ['A07'] },
        { id: 'A07', map: 'sup', x: 172, y: 907, type: 'safe', monsterType: '', level: 0, next: ['A08'] },
        { id: 'A08', map: 'sup', x: 231, y: 922, type: 'battle', monsterType: 'woods', level: 2, next: ['A09'] },
        { id: 'A09', map: 'sup', x: 291, y: 933, type: 'battle', monsterType: 'woods', level: 2, next: ['A10'] },
        { id: 'A10', map: 'sup', x: 350, y: 933, type: 'battle', monsterType: 'woods', level: 3, next: ['A11'] },
        { id: 'A11', map: 'sup', x: 410, y: 929, type: 'battle', monsterType: 'woods', level: 3, next: ['A12'] },
        { id: 'A12', map: 'sup', x: 467, y: 912, type: 'battle', monsterType: 'woods', level: 3, next: ['A13'] },
        { id: 'A13', map: 'sup', x: 510, y: 881, type: 'battle', monsterType: 'woods', level: 3, next: ['S03'] },
        { id: 'S03', map: 'sup', x: 532, y: 828, type: 'fork', monsterType: '', level: 0, next: ['SS1','N01'], labels: {"SS1":"Margem sul — curta","N01":"Contornar o lago pelo norte — longa, com baú"} },
        { id: 'SS1', map: 'sup', x: 596, y: 790, type: 'battle', monsterType: 'woods', level: 3, next: ['SS1~1'] },
        { id: 'SS2', map: 'sup', x: 667, y: 757, type: 'battle', monsterType: 'woods', level: 4, next: ['SS2~1'] },
        { id: 'SS3', map: 'sup', x: 739, y: 729, type: 'battle', monsterType: 'woods', level: 4, next: ['SS3~1'] },
        { id: 'SS4', map: 'sup', x: 810, y: 700, type: 'battle', monsterType: 'woods', level: 4, next: ['SS4~1'] },
        { id: 'SS5', map: 'sup', x: 876, y: 666, type: 'battle', monsterType: 'woods', level: 4, next: ['SS5~1'] },
        { id: 'N01', map: 'sup', x: 499, y: 772, type: 'battle', monsterType: 'woods', level: 3, next: ['N02'] },
        { id: 'N02', map: 'sup', x: 470, y: 739, type: 'battle', monsterType: 'woods', level: 3, next: ['N03'] },
        { id: 'N03', map: 'sup', x: 422, y: 691, type: 'battle', monsterType: 'woods', level: 3, next: ['N04'] },
        { id: 'N04', map: 'sup', x: 365, y: 653, type: 'battle', monsterType: 'woods', level: 3, next: ['N05'] },
        { id: 'N05', map: 'sup', x: 340, y: 613, type: 'rest', monsterType: '', level: 0, next: ['N06'] },
        { id: 'N06', map: 'sup', x: 355, y: 565, type: 'battle', monsterType: 'woods', level: 4, next: ['N07'] },
        { id: 'N07', map: 'sup', x: 410, y: 525, type: 'battle', monsterType: 'woods', level: 4, next: ['N08'] },
        { id: 'N08', map: 'sup', x: 464, y: 483, type: 'battle', monsterType: 'woods', level: 4, next: ['N09'] },
        { id: 'N09', map: 'sup', x: 517, y: 456, type: 'battle', monsterType: 'woods', level: 4, next: ['N10'] },
        { id: 'N10', map: 'sup', x: 565, y: 439, type: 'battle', monsterType: 'woods', level: 4, next: ['N11'] },
        { id: 'N11', map: 'sup', x: 625, y: 439, type: 'battle', monsterType: 'woods', level: 4, next: ['N12'] },
        { id: 'N12', map: 'sup', x: 685, y: 441, type: 'battle', monsterType: 'woods', level: 4, next: ['N13'] },
        { id: 'N13', map: 'sup', x: 753, y: 443, type: 'battle', monsterType: 'woods', level: 5, next: ['N14'] },
        { id: 'N14', map: 'sup', x: 813, y: 464, type: 'battle', monsterType: 'woods', level: 5, next: ['N15'] },
        { id: 'N15', map: 'sup', x: 865, y: 496, type: 'battle', monsterType: 'woods', level: 5, next: ['N16'] },
        { id: 'N16', map: 'sup', x: 906, y: 543, type: 'battle', monsterType: 'woods', level: 5, next: ['N17'] },
        { id: 'N17', map: 'sup', x: 920, y: 591, type: 'battle', monsterType: 'woods', level: 5, next: ['N18'] },
        { id: 'N18', map: 'sup', x: 903, y: 634, type: 'reward', monsterType: '', level: 0, next: ['M01'] },
        { id: 'M01', map: 'sup', x: 965, y: 657, type: 'rest', monsterType: '', level: 0, next: ['M01~1'] },
        { id: 'E01', map: 'sup', x: 1035, y: 704, type: 'battle', monsterType: 'ruins', level: 5, next: ['E01~1'] },
        { id: 'E02', map: 'sup', x: 1103, y: 747, type: 'battle', monsterType: 'ruins', level: 5, next: ['E02~1'] },
        { id: 'E03', map: 'sup', x: 1174, y: 785, type: 'battle', monsterType: 'ruins', level: 6, next: ['E03~1'] },
        { id: 'E04', map: 'sup', x: 1246, y: 809, type: 'battle', monsterType: 'ruins', level: 6, next: ['E05'] },
        { id: 'E05', map: 'sup', x: 1311, y: 823, type: 'battle', monsterType: 'ruins', level: 6, next: ['E06'] },
        { id: 'E06', map: 'sup', x: 1371, y: 831, type: 'fork', monsterType: '', level: 0, next: ['B01','T01'], labels: {"B01":"Subir pela escada do muro — direto","T01":"Descer a trilha sul até o baú — ida e volta"} },
        { id: 'B01', map: 'sup', x: 1389, y: 779, type: 'battle', monsterType: 'ruins', level: 6, next: ['B02'] },
        { id: 'B02', map: 'sup', x: 1385, y: 735, type: 'battle', monsterType: 'ruins', level: 7, next: ['B03'] },
        { id: 'B03', map: 'sup', x: 1383, y: 693, type: 'battle', monsterType: 'ruins', level: 7, next: ['B04'] },
        { id: 'B04', map: 'sup', x: 1389, y: 649, type: 'battle', monsterType: 'ruins', level: 7, next: ['G01'] },
        { id: 'T01', map: 'sup', x: 1400, y: 878, type: 'battle', monsterType: 'woods', level: 6, next: ['T02'] },
        { id: 'T02', map: 'sup', x: 1414, y: 938, type: 'battle', monsterType: 'woods', level: 6, next: ['T03'] },
        { id: 'T03', map: 'sup', x: 1408, y: 1000, type: 'battle', monsterType: 'woods', level: 6, next: ['T03~1'] },
        { id: 'T04', map: 'sup', x: 1373, y: 1073, type: 'reward', monsterType: '', level: 0, next: ['T04~1'] },
        { id: 'T03r', map: 'sup', x: 1442, y: 1002, type: 'battle', monsterType: 'woods', level: 6, next: ['T02r'] },
        { id: 'T02r', map: 'sup', x: 1449, y: 940, type: 'rest', monsterType: '', level: 0, next: ['T01r'] },
        { id: 'T01r', map: 'sup', x: 1436, y: 881, type: 'battle', monsterType: 'woods', level: 7, next: ['T01r~1'] },
        { id: 'G01', map: 'sup', x: 1389, y: 595, type: 'gate', monsterType: '', level: 0, next: ['K01'] },
        { id: 'S01~1', map: 'sup', x: 252, y: 787, type: 'safe', monsterType: '', level: 0, next: ['A01'] },
        { id: 'SS1~1', map: 'sup', x: 632, y: 774, type: 'battle', monsterType: 'woods', level: 3, next: ['SS2'] },
        { id: 'SS2~1', map: 'sup', x: 703, y: 743, type: 'battle', monsterType: 'woods', level: 4, next: ['SS3'] },
        { id: 'SS3~1', map: 'sup', x: 775, y: 715, type: 'battle', monsterType: 'woods', level: 4, next: ['SS4'] },
        { id: 'SS4~1', map: 'sup', x: 843, y: 683, type: 'battle', monsterType: 'woods', level: 4, next: ['SS5'] },
        { id: 'SS5~1', map: 'sup', x: 921, y: 662, type: 'battle', monsterType: 'woods', level: 5, next: ['M01'] },
        { id: 'M01~1', map: 'sup', x: 1000, y: 681, type: 'battle', monsterType: 'ruins', level: 5, next: ['E01'] },
        { id: 'E01~1', map: 'sup', x: 1069, y: 726, type: 'battle', monsterType: 'ruins', level: 5, next: ['E02'] },
        { id: 'E02~1', map: 'sup', x: 1139, y: 766, type: 'battle', monsterType: 'ruins', level: 6, next: ['E03'] },
        { id: 'E03~1', map: 'sup', x: 1210, y: 797, type: 'battle', monsterType: 'ruins', level: 6, next: ['E04'] },
        { id: 'T03~1', map: 'sup', x: 1391, y: 1037, type: 'battle', monsterType: 'woods', level: 6, next: ['T04'] },
        { id: 'T04~1', map: 'sup', x: 1408, y: 1038, type: 'battle', monsterType: 'woods', level: 6, next: ['T03r'] },
        { id: 'T01r~1', map: 'sup', x: 1413, y: 830, type: 'battle', monsterType: 'woods', level: 7, next: ['B01'] },
        { id: 'K01', map: 'tomb', x: 226, y: 303, type: 'start', monsterType: '', level: 0, next: ['K02'] },
        { id: 'K02', map: 'tomb', x: 304, y: 347, type: 'battle', monsterType: 'undead', level: 7, next: ['K03'] },
        { id: 'K03', map: 'tomb', x: 381, y: 411, type: 'battle', monsterType: 'undead', level: 7, next: ['K04'] },
        { id: 'K04', map: 'tomb', x: 459, y: 458, type: 'battle', monsterType: 'undead', level: 8, next: ['K05'] },
        { id: 'K05', map: 'tomb', x: 536, y: 497, type: 'battle', monsterType: 'undead', level: 8, next: ['K06'] },
        { id: 'K06', map: 'tomb', x: 614, y: 524, type: 'battle', monsterType: 'undead', level: 8, next: ['K07'] },
        { id: 'K07', map: 'tomb', x: 715, y: 524, type: 'battle', monsterType: 'undead', level: 8, next: ['K08'] },
        { id: 'K08', map: 'tomb', x: 781, y: 569, type: 'battle', monsterType: 'undead', level: 8, next: ['K09'] },
        { id: 'K09', map: 'tomb', x: 840, y: 613, type: 'battle', monsterType: 'undead', level: 8, next: ['KF'] },
        { id: 'KF', map: 'tomb', x: 906, y: 652, type: 'fork', monsterType: '', level: 0, next: ['U01','L01'], labels: {"U01":"Corredor dos nichos — curto","L01":"Caverna inferior — longa, com baú"} },
        { id: 'U01', map: 'tomb', x: 948, y: 571, type: 'battle', monsterType: 'undead', level: 9, next: ['U02'] },
        { id: 'U02', map: 'tomb', x: 995, y: 512, type: 'battle', monsterType: 'undead', level: 9, next: ['U03'] },
        { id: 'U03', map: 'tomb', x: 1079, y: 491, type: 'battle', monsterType: 'undead', level: 9, next: ['U04'] },
        { id: 'U04', map: 'tomb', x: 1162, y: 470, type: 'battle', monsterType: 'undead', level: 9, next: ['U05'] },
        { id: 'U05', map: 'tomb', x: 1246, y: 443, type: 'battle', monsterType: 'undead', level: 9, next: ['U06'] },
        { id: 'U06', map: 'tomb', x: 1323, y: 414, type: 'battle', monsterType: 'undead', level: 9, next: ['U07'] },
        { id: 'U07', map: 'tomb', x: 1395, y: 381, type: 'battle', monsterType: 'undead', level: 9, next: ['U08'] },
        { id: 'U08', map: 'tomb', x: 1448, y: 347, type: 'battle', monsterType: 'undead', level: 10, next: ['U09'] },
        { id: 'U09', map: 'tomb', x: 1526, y: 363, type: 'battle', monsterType: 'undead', level: 10, next: ['M02'] },
        { id: 'L01', map: 'tomb', x: 936, y: 726, type: 'battle', monsterType: 'caves', level: 8, next: ['L02'] },
        { id: 'L02', map: 'tomb', x: 987, y: 800, type: 'battle', monsterType: 'caves', level: 8, next: ['L03'] },
        { id: 'L03', map: 'tomb', x: 1043, y: 866, type: 'battle', monsterType: 'caves', level: 8, next: ['L04'] },
        { id: 'L04', map: 'tomb', x: 1126, y: 934, type: 'battle', monsterType: 'caves', level: 8, next: ['L05'] },
        { id: 'L05', map: 'tomb', x: 1198, y: 1000, type: 'reward', monsterType: '', level: 0, next: ['L06'] },
        { id: 'L06', map: 'tomb', x: 1287, y: 976, type: 'battle', monsterType: 'caves', level: 8, next: ['L07'] },
        { id: 'L07', map: 'tomb', x: 1395, y: 958, type: 'battle', monsterType: 'caves', level: 8, next: ['L08'] },
        { id: 'L08', map: 'tomb', x: 1514, y: 934, type: 'rest', monsterType: '', level: 0, next: ['L09'] },
        { id: 'L09', map: 'tomb', x: 1633, y: 922, type: 'battle', monsterType: 'caves', level: 9, next: ['L10'] },
        { id: 'L10', map: 'tomb', x: 1716, y: 923, type: 'battle', monsterType: 'caves', level: 9, next: ['L11'] },
        { id: 'L11', map: 'tomb', x: 1788, y: 912, type: 'battle', monsterType: 'caves', level: 9, next: ['L12'] },
        { id: 'L12', map: 'tomb', x: 1841, y: 878, type: 'battle', monsterType: 'caves', level: 9, next: ['L13'] },
        { id: 'L13', map: 'tomb', x: 1889, y: 827, type: 'battle', monsterType: 'caves', level: 9, next: ['L14'] },
        { id: 'L14', map: 'tomb', x: 1907, y: 771, type: 'battle', monsterType: 'caves', level: 9, next: ['L15'] },
        { id: 'L15', map: 'tomb', x: 1895, y: 714, type: 'battle', monsterType: 'caves', level: 9, next: ['L16'] },
        { id: 'L16', map: 'tomb', x: 1841, y: 666, type: 'battle', monsterType: 'caves', level: 9, next: ['L17'] },
        { id: 'L17', map: 'tomb', x: 1776, y: 601, type: 'battle', monsterType: 'caves', level: 10, next: ['L18'] },
        { id: 'L18', map: 'tomb', x: 1716, y: 545, type: 'battle', monsterType: 'caves', level: 10, next: ['L19'] },
        { id: 'L19', map: 'tomb', x: 1669, y: 506, type: 'battle', monsterType: 'caves', level: 10, next: ['M02'] },
        { id: 'M02', map: 'tomb', x: 1627, y: 438, type: 'rest', monsterType: '', level: 0, next: ['BOSS'] },
        { id: 'BOSS', map: 'tomb', x: 1695, y: 395, type: 'boss', monsterType: 'undead', level: 10, next: [] },

];

export const whisperingForestBoard: StoryBoard = {
    maps: [
        { id: 'sup', image: '/assets/boards/whispering-forest/superficie.webp', width: 2000, height: 1115 },
        { id: 'tomb', image: '/assets/boards/whispering-forest/catacumbas.webp', width: 2000, height: 1115 }
    ],
    nodes,
    startNodeId: 'S01',
    bossId: 10003,
    intro: 'Vocês chegam a Pedraverde, vila à beira da Floresta Sussurrante. Uma névoa gelada e viva engole a mata, e os caçadores que entraram nela não foram mortos: foram mudados. Helga, a chefe da guarda, pede que sigam as trilhas, encontrem a tumba élfica de onde vem a maldição e a destruam antes que ela alcance a vila. Rolem o d6 e avancem pelo tabuleiro.',
    gateText: 'Diante do portão guardado por gárgulas, a névoa se adensa e se parte como uma cortina. Vocês descem às catacumbas élficas, onde o ar pesa e a escuridão parece respirar.',
    restText: 'Um refúgio seguro. Vocês podem descansar, cuidar dos ferimentos e se preparar para o que vem a seguir.',
    rewardText: 'Um tesouro! Cada aventureiro pode abrir mais um baú.',
    endText: 'O cristal negro estala uma última vez e as runas se apagam. A névoa recua e o amanhecer encontra uma Floresta Sussurrante enfim em paz. Em Pedraverde, Helga os recebe em silêncio: a maldição acabou.'
};
